[WIP] toArray and toSeq methods
ThoughtWorksInc/OpenCL.scala pull request #156
Opened 2018-05-04 23:00 UTC by evanhaldane

fixes ThoughtWorksInc/Compute.scala/issues/130

2018-05-04 23:04 UTC, evanhaldane commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeArray(a:Array[_], b:Array[Int]): Array[_] = {
Needs a check that the product of the dimensions in `b` equals the length of `a`

2018-05-04 23:06 UTC, evanhaldane commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeArray(a:Array[_], b:Array[Int]): Array[_] = {
also renaming those variables to something informative

2018-05-05 06:03 UTC, Atry requested changes

2018-05-05 06:03 UTC, Atry commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeArray(array:Array[_], shape:Array[Int]): Array[_] = {
When `shape` is `Array.empty`, the tensor is a scalar value, not an `Array`.

This method should either throw an exception for scalar value, or change the return type.

2018-05-05 06:03 UTC, Atry commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeSeq(a:Seq[_], b:Array[Int]): Seq[_] = {
When `shape` is `Array.empty`, the tensor is a scalar value, not a `Seq`.

This method should either throw an exception for scalar value, or change the return type.

2018-05-05 06:03 UTC, Atry commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    def toArray = {flatArray.map {z=> reshapeArray(z, shape)}}
Since `toArray` or `toSeq` in Scala collection library is not asynchronous, the name `toArray` will surprise people if it returns a `Future`.

Maybe we should rename it to `readArray`, which seems like a rather expensive operation.

2018-05-07 15:33 UTC, evanhaldane commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeArray(array:Array[_], shape:Array[Int]): Array[_] = {
Right! If scalars are considered distinct from 1d arrays, then I think it makes sense that the function `readArray` would throw an exception.

2018-05-07 21:39 UTC, Atry commented on Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala
> +    private[Tensors] def reshapeArray(array:Array[_], shape:Array[Int]): Array[_] = {
If scalars are considered distinct from 1d arrays, why 1D arrays and 2D array shares the same method? Considering the `Array[_]` return type is not actually usable without an `anInstanceOf`.

There are three options:

1. Create two methods for scalars and 1+ dimensional arrays, respectively
2. Create one `Any` methods for both scalars and 1+ dimensional arrays
3. Create n methods for different rank of tensors, respectively

What do you think?

2018-05-08 18:22 UTC, evanhaldane commented
You're right that the user would need to know the number of dimensions and cast with `asInstanceOf` anyway, so how about this type of approach with explicit methods, sort of the same way `Array.ofDim` works?

(I haven't touched `toSeq` yet. Let me know what you think)

2018-05-09 01:16 UTC, Atry commented
The best solution is changing `Tensor` to `Tensor[A]`, where `A` could be `Float`, `Array[Float]`, `Array[Array[Float]]` etc.

2018-05-09 01:59 UTC, evanhaldane commented
Do you think it is worth having to parametrize `Tensor` everywhere else for the purpose of solving this issue? Are there other advantages to that approach? Determining the type parameter for operations that change the shape of the tensor could end up being problematic.

What do you not like about the `read2DArray`, `read3DArray` approach?

2018-05-09 02:01 UTC, evanhaldane commented
Ah I just saw your edited comment. 

I think `read2DArray`, `read3DArray`, etc. is probably better than the `Any` approach, as that would be almost unusable beyond 5 dimensions anyway.

2018-05-09 02:03 UTC, Atry commented
Eventually we will need type parameters for `Tensor`, when implementing other element types: https://github.com/ThoughtWorksInc/Compute.scala/issues/104

2018-05-09 02:08 UTC, Atry commented
In practice the length of a tensor parameter may vary in multiple calls to a function, e.g. different batch size when running a neural network.

However the number of dimension of a tensor is usually stable. It is reasonable to statically type it.

2018-05-09 02:09 UTC, Atry commented
If we will eventually add the type parameter for tensor, the `readScalar` / `read2DArray` / `read3DArray` approach is just a temporary solution.

2018-05-09 02:24 UTC, evanhaldane commented
Right. Makes sense, though many changes necessary and some issues to solve (e.g. the function `split`).

For now should we go with the (probably temporary) solution and address those issues as part of #104?

2018-05-09 02:50 UTC, Atry commented
If in the future it will become the following type signature:

``` scala
trait Tensor[A] {
  def read: Future[A]
}
```

Then I thought a sane type signature for now could be:

``` scala
trait Tensor {
  def read: Future[Any]
}
```

Do you think the `Seq` / `Array` distinct is important here?

2018-05-09 02:50 UTC, Atry commented
Which type is preferred, `Seq` or `Array`?

2018-05-09 02:52 UTC, Atry commented
N-dimensional `Seq` can be potentially more efficient by creating nested view of underlying flat array, avoiding memory copy.

2018-05-09 02:56 UTC, Atry commented
We had create some views for `Tensor.split`: https://github.com/ThoughtWorksInc/Compute.scala/blob/f893fde/Tensors/src/main/scala/com/thoughtworks/compute/Tensors.scala#L1060

2018-05-09 03:07 UTC, evanhaldane commented
If the main purpose of `toArray` or `toSeq` is to interact with other code, then is efficiency relevant? If the user needs an `Array` because of some other library or code base, then that's what matters, right?

2018-05-09 03:10 UTC, evanhaldane commented
or were you asking about the underlying parametrization of `Tensor`?

2018-05-09 03:48 UTC, Atry commented
There are some issues to address in this PR:

1. Which type is preferred when reading a tensor to JVM type, `Seq` or `Array`, or both?
2. What type signature is for the reading method(s)?

2018-05-09 19:18 UTC, evanhaldane commented
1. Both.
2. I've added the appropriate signature for each of the individual `read` methods.

2018-05-10 02:03 UTC, Atry commented
I can merge this PR for now.
Would you mind if those `read*DArray` methods will be replaced to a single `read` method when the type parameter is introduced for `Tensor`? @evanhaldane

2018-05-10 02:05 UTC, evanhaldane commented
Sure! I've subscribed to notifications on #104.

2018-05-10 02:07 UTC, Atry commented
The incoming change will break backward compatibility.... It's OK since the version number is still pre 1.0.

2018-05-10 02:07 UTC, Atry approved these changes

2018-05-10 02:09 UTC, Atry commented
Please remove  `[WIP]` in the title and rebase it according to the git HEAD before it is ready to merge.

2018-05-25 05:13 UTC, merged

2018-05-25 05:13 UTC, Atry commented
Merged.

Thank you! @evanhaldane